trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
    - job: BuildJob
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            projects: '**/*.csproj'
            arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'

- stage: Deploy
  dependsOn: Build
  jobs:
    - job: DeployFunctionApp
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: 'drop'
            path: '$(Pipeline.Workspace)/drop'

        - script: |
            ls -la $(Pipeline.Workspace)/drop
          displayName: 'List contents of drop directory'

        - task: AzureFunctionApp@1
          inputs:
            azureSubscription: 'apim'
            appType: 'functionApp'
            appName: 'FuncAppApim2'
            package: '$(Pipeline.Workspace)/drop/*.zip'
            deploymentMethod: 'zipDeploy'

        - task: AzureCLI@2
          inputs:
            azureSubscription: 'apim'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az apim api create --service-name 'myApiManagement62stc5dcjqttq' \
              --resource-group 'marat-rg' \
              --api-id '/subscriptions/3d6898ce-4685-4181-93df-efa0373422f3/resourceGroups/marat-rg/providers/Microsoft.Web/sites/FuncAppApim2' \
              --path 'https://myapimanagement62stc5dcjqttq.azure-api.net' \
              --display-name 'FuncAppApim2' \
              --protocols https \
              --service-url 'https://funcappapim2.azurewebsites.net' \
              --subscription-required false
